AWS_ACCESS_KEY = 'AKIA4VDBLXJZ5NU2RQMN'
AWS_SECRET_KEY = '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'
GROQ_API_KEY = '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'
GOOGLE_API_KEY = 'AIzaSyA0MumXQkNrZLIUiBWDv1pFMgspIMN4zM4'